services:
  postgres:
    container_name: postgres
    image: postgres
    restart: always

    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_NAME}
    volumes:
      - ${POSTGRES_VOLUME}:/var/lib/postgresql/data
    networks:
      - apigateway_network
  redis:
    image: redis
    restart: always
    container_name: redis
    #ports:
    #  - '6379:6379'
    volumes:
      - ${REDIS_VOLUME}:/var/lib/redis
    networks:
      - apigateway_network
  nats:
    image: nats
    restart: always
    container_name: nats
    #ports:
    #  - '4222:4222'
    #  - '8222:8222'
    networks:
      - apigateway_network
networks:
  apigateway_network:
    name: apigateway_network
    driver: bridge
